// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntarofjcfwcbinjbnxpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50YXJvZmpjZndjYmluamJueHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzEwNTYsImV4cCI6MjA2NzYwNzA1Nn0.ZQwrIEeL5dBD8IAkw9bD3cl6FgvQrKFVkj-P8M9fQSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});